### ISSUE TITLE
URI must have scheme and server

### ISSUE THREAD

**Issue by lodygens** [lodygens/xtremweb-hep#13]
URI(String) should set default scheme and server, if not found in the provided String

**Comment by mocamircea** [comment]
Otherwise, this is a valid URI but without a scheme or server. This leads to incapacity of downloading data.

**Comment by mocamircea** [comment]
Example of job that tries to use data URI without scheme and server:
`<?xml version='1.0' encoding='UTF-8'?><get><work><uid>5cf037c3-403c-4fdf-b8eb-83a945b2d628</uid><owneruid>e6052959-b809-457a-a974-427aace56ccb</owneruid><accessrights>0x755</accessrights><errormsg>IOError_:_can_t_download_work_:can_t_download_dirin_(scheme_is_null)</errormsg><isservice>false</isservice><appuid>cb841a3f-15ab-470e-b3a5-3c80d7732d73</appuid><returncode>0</returncode><cmdline>evolutions=2 clusters=3 minfit=2 file=data</cmdline><dirinuri>72762f47-dfee-4a99-bf3b-64b2788047a6</dirinuri><arrivaldate>2017-06-28 14:47:46</arrivaldate><readydate>2017-06-28 14:47:46</readydate><sendtoclient>false</sendtoclient><local>true</local><active>true</active><replications>0</replications><totalr>0</totalr><sizer>0</sizer><maxretry>10</maxretry><maxwallclocktime>21600</maxwallclocktime><retry>0</retry><diskspace>0</diskspace><minmemory>0</minmemory><mincpuspeed>0</mincpuspeed><status>ERROR</status><minfreemassstorage>0</minfreemassstorage></work></get>`

**Comment by lodygens** [comment]
This is solved by commit [e3a5a9632f8a6890513e019194b4639e467e048b](https://github.com/lodygens/xtremweb-hep/commit/e3a5a9632f8a6890513e019194b4639e467e048b)
