### ISSUE TITLE
Stdin

### ISSUE THREAD

**Issue by JorgePC38** [lodygens/xtremweb-hep#7]
When doing a xwsubmit, the way to redirect the standard input and providing a file to the app is to use the option --xwstdin and not '<' as it is mentioned in the 'help'

**Comment by lodygens** [comment]
re-tested and works correctly

the only is that the help display something wrong :')

**Comment by lodygens** [comment]
re-tested and works correctly

the only is that the help display something wrong :')

**Comment by lodygens** [comment]
Corrected by https://github.com/lodygens/xtremweb-hep/commit/009faab97e5079f6f40de99900bc820b9a6ac9fd
